CREATE TABLE IF NOT EXISTS User (
	id TEXT NOT NULL,
	wallet TEXT NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Listing (
	id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	addr TEXT NOT NULL,
	desc TEXT NOT NULL,
	price TEXT NOT NULL,
	images TEXT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES User (id),
	PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Payments (
	id TEXT NOT NULL,
	amount TEXT NOT NULL,
	paid BOOLEAN NOT NULL,
);
